// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keepaconfig/keepaconfig.proto

package keepaconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeepaConfig struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BaseURL              string   `protobuf:"bytes,3,opt,name=BaseURL,proto3" json:"BaseURL,omitempty"`
	AccessKey            string   `protobuf:"bytes,4,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	Domain               int32    `protobuf:"varint,5,opt,name=Domain,proto3" json:"Domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepaConfig) Reset()         { *m = KeepaConfig{} }
func (m *KeepaConfig) String() string { return proto.CompactTextString(m) }
func (*KeepaConfig) ProtoMessage()    {}
func (*KeepaConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_398ca50dc5449c49, []int{0}
}

func (m *KeepaConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepaConfig.Unmarshal(m, b)
}
func (m *KeepaConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepaConfig.Marshal(b, m, deterministic)
}
func (m *KeepaConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepaConfig.Merge(m, src)
}
func (m *KeepaConfig) XXX_Size() int {
	return xxx_messageInfo_KeepaConfig.Size(m)
}
func (m *KeepaConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepaConfig.DiscardUnknown(m)
}

var xxx_messageInfo_KeepaConfig proto.InternalMessageInfo

func (m *KeepaConfig) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *KeepaConfig) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *KeepaConfig) GetBaseURL() string {
	if m != nil {
		return m.BaseURL
	}
	return ""
}

func (m *KeepaConfig) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *KeepaConfig) GetDomain() int32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func init() {
	proto.RegisterType((*KeepaConfig)(nil), "keepaconfig.KeepaConfig")
}

func init() { proto.RegisterFile("keepaconfig/keepaconfig.proto", fileDescriptor_398ca50dc5449c49) }

var fileDescriptor_398ca50dc5449c49 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0x4e, 0x4d, 0x2d,
	0x48, 0x4c, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x47, 0x62, 0xeb, 0x15, 0x14, 0xe5, 0x97, 0xe4,
	0x0b, 0x71, 0x23, 0x09, 0x29, 0xb5, 0x32, 0x72, 0x71, 0x7b, 0x83, 0xf8, 0xce, 0x60, 0xbe, 0x10,
	0x1f, 0x17, 0x93, 0xa7, 0x8b, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x93, 0xa7, 0x8b, 0x90,
	0x18, 0x17, 0x5b, 0x68, 0x71, 0x6a, 0x91, 0xa7, 0x8b, 0x04, 0x13, 0x58, 0x0c, 0xca, 0x13, 0x92,
	0xe0, 0x62, 0x77, 0x4a, 0x2c, 0x4e, 0x0d, 0x0d, 0xf2, 0x91, 0x60, 0x06, 0x4b, 0xc0, 0xb8, 0x42,
	0x32, 0x5c, 0x9c, 0x8e, 0xc9, 0xc9, 0xa9, 0xc5, 0xc5, 0xde, 0xa9, 0x95, 0x12, 0x2c, 0x60, 0x39,
	0x84, 0x00, 0xc8, 0x3c, 0x97, 0xfc, 0xdc, 0xc4, 0xcc, 0x3c, 0x09, 0x56, 0x05, 0x46, 0x0d, 0xd6,
	0x20, 0x28, 0xcf, 0xc9, 0x20, 0x4a, 0x2f, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f,
	0x57, 0xbf, 0xb8, 0x32, 0x2f, 0x39, 0xad, 0xb4, 0xa4, 0xb4, 0x28, 0x15, 0xe2, 0x7e, 0x7d, 0xb0,
	0xcb, 0x93, 0x91, 0x3d, 0x93, 0xc4, 0x06, 0x16, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf2,
	0x05, 0x65, 0xc2, 0xee, 0x00, 0x00, 0x00,
}
